"""initial dashboard schema

Revision ID: 09ab60d66140
Revises: 
Create Date: 2026-04-25 17:14:17.867439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ab60d66140'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_activity',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=128), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('time', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents_global',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('health', sa.Enum('healthy', 'training', 'degraded', 'offline', name='agent_health_enum'), nullable=False),
    sa.Column('uptime', sa.String(length=16), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('last_action', sa.String(length=256), nullable=False),
    sa.Column('last_run', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commute',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('eta', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('dest', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_commute_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_briefing',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('greeting', sa.String(length=128), nullable=False),
    sa.Column('date_label', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_daily_briefing_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('context', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.Enum('github', 'gmail', 'notion', 'linear', 'slack', 'calendar', name='source_enum'), nullable=False),
    sa.Column('waiting_since', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domains',
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('tagline', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('start', sa.String(length=32), nullable=False),
    sa.Column('duration', sa.String(length=32), nullable=False),
    sa.Column('calendar', sa.Enum('work', 'personal', 'family', 'health', name='calendar_tag_enum'), nullable=False),
    sa.Column('source', sa.Enum('Google', 'Apple', 'Outlook', name='event_source_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('focus_now',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('subtitle', sa.String(length=256), nullable=False),
    sa.Column('context', sa.String(length=1024), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_focus_now_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_habits',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('delta', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('knowledge_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nav_items',
    sa.Column('path', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=True),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('path')
    )
    op.create_table('news_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'warn', 'info', 'ok', name='severity_enum'), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=False),
    sa.Column('time', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quick_actions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('hint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source', sa.Enum('github', 'gmail', 'notion', 'linear', 'slack', 'calendar', name='source_enum'), nullable=False),
    sa.Column('due', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Enum('p0', 'p1', 'p2', 'p3', name='priority_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('temp', sa.String(length=16), nullable=False),
    sa.Column('condition', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_weather_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('health', sa.Enum('healthy', 'training', 'degraded', 'offline', name='agent_health_enum'), nullable=False),
    sa.Column('uptime', sa.String(length=16), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('last_action', sa.String(length=256), nullable=False),
    sa.Column('last_run', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_slug'], ['domains.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_agents_domain_slug', 'domain_agents', ['domain_slug'], unique=False)
    op.create_table('domain_applications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('domain_slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('live', 'beta', 'planned', name='application_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_slug'], ['domains.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_applications_domain_slug', 'domain_applications', ['domain_slug'], unique=False)
    op.create_table('domain_feed_rows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('domain_slug', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('time', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_slug'], ['domains.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_feed_rows_domain_slug', 'domain_feed_rows', ['domain_slug'], unique=False)
    op.create_table('domain_kpis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_slug', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('delta', sa.String(length=128), nullable=True),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_slug'], ['domains.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_kpis_domain_slug', 'domain_kpis', ['domain_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_domain_kpis_domain_slug', table_name='domain_kpis')
    op.drop_table('domain_kpis')
    op.drop_index('ix_domain_feed_rows_domain_slug', table_name='domain_feed_rows')
    op.drop_table('domain_feed_rows')
    op.drop_index('ix_domain_applications_domain_slug', table_name='domain_applications')
    op.drop_table('domain_applications')
    op.drop_index('ix_domain_agents_domain_slug', table_name='domain_agents')
    op.drop_table('domain_agents')
    op.drop_table('weather')
    op.drop_table('tasks')
    op.drop_table('quick_actions')
    op.drop_table('notifications')
    op.drop_table('news_items')
    op.drop_table('nav_items')
    op.drop_table('knowledge_suggestions')
    op.drop_table('health_habits')
    op.drop_table('focus_now')
    op.drop_table('events')
    op.drop_table('domains')
    op.drop_table('decisions')
    op.drop_table('daily_briefing')
    op.drop_table('commute')
    op.drop_table('agents_global')
    op.drop_table('agent_activity')
    # ### end Alembic commands ###
