"""ontology entities and relationships (FEAT-144 slice 1)

Revision ID: o1l2m3n4a5b6
Revises: l1i2j3k4a5b6
Create Date: 2026-09-14 00:00:00.000000

Adds ``ontology_entities`` and ``ontology_relationships`` — a minimal
knowledge graph derived from ingested GitHub activity (person entities,
project entities, and ``contributed_to`` edges between them).

IMMUTABILITY (per .claude/rules/database.md)
---------------------------------------------
Do NOT edit this file once merged. If a follow-up slice needs to widen
``entity_type`` (e.g. to add ``thread``/``event`` for Gmail/Calendar) or
``relationship_type``, do it with ``ALTER TABLE ... DROP CONSTRAINT`` /
``ADD CONSTRAINT`` in a NEW migration.

SCOPE RATIONALE (BLOCKER 2 from the FEAT-144 retry requirement)
-----------------------------------------------------------------
``entity_type`` is restricted to ``person`` / ``project`` and
``relationship_type`` to ``contributed_to`` only, because this slice
derives its graph exclusively from GitHub activity. Gmail/Calendar
relationships would need ``thread``/``event`` target entity types that
don't exist yet — that is an explicit follow-up slice, not scope creep
here. The full source -> (source_entity_type, relationship_type,
target_entity_type) mapping this slice actually produces is exactly one
row: github -> (person, contributed_to, project).

NAMING DEVIATION
------------------
The column below is named ``classification_checked_at``, NOT
``visibility_checked_at`` as written in the original FEAT-141
requirement text. This is a deliberate deviation, not an oversight.

UUID RATIONALE
-----------------
Primary keys use ORM-side ``default=uuid.uuid4`` (see
``backend/src/models/ontology.py``), not ``gen_random_uuid()``. Every
other table in this codebase uses the ORM-side default, and no raw-SQL
insert path in this slice omits ``id`` (the CLI script and the
extraction service both go through SQLAlchemy Core, which fills the
Python-side default) — so there is no reason to be the first exception.

GUC RESIDUAL RISKS
---------------------
The visibility ratchet below is enforced entirely inside this trigger
via the transaction-local GUC ``app.allow_visibility_promotion``. Two
things can bypass it that PL/pgSQL cannot see or prevent, and are
therefore operational controls, not code controls:
  * ``ALTER DATABASE ... SET app.allow_visibility_promotion = 'true'``
    or ``ALTER ROLE ... SET ...`` sets the GUC at a scope the trigger
    cannot distinguish from a legitimate transaction-local grant.
  * A superuser running ``ALTER TABLE ... DISABLE TRIGGER`` bypasses the
    ratchet entirely.

WHY set_config() OVER SET LOCAL (for future promotion callers)
------------------------------------------------------------------
This slice's extraction service (see below) never needs to set this GUC
at all, but future callers that legitimately promote a row should use
``set_config('app.allow_visibility_promotion', 'true', true)`` rather
than ``SET LOCAL``: ``SET LOCAL`` accepts no bind parameters, so any
dynamic form would require string interpolation, which
.claude/rules/database.md forbids. Separately,
``backend/src/models/db_pooler_guard.py`` mandates session-mode
Supavisor pooling — a session-scoped GUC (as opposed to the
transaction-scoped third argument of ``set_config``) would survive
connection checkout and silently disable the ratchet for unrelated
later requests sharing that pooled connection.

WHY THE EXTRACTION SERVICE NEVER SETS THE GUC
-------------------------------------------------
``backend/src/services/ingestion/ontology_extract.py`` never calls
``set_config('app.allow_visibility_promotion', ...)``. Every write it
performs is already exempt from the ratchet: (a) entity INSERT omits
``visibility``, so ``server_default='private'`` applies and the INSERT
arm below only ever sees ``'private'``; (b) entity ``ON CONFLICT DO
UPDATE`` explicitly excludes ``visibility`` from its SET clause, so
``NEW.visibility = OLD.visibility`` and the UPDATE arm's equality check
passes without needing the GUC; (c) the relationship upsert is
``DO NOTHING`` and never reaches an UPDATE at all. Setting the GUC here
would disable the ratchet across the only writer path in a slice whose
entire purpose is the ratchet — do not add it "for safety".

VISIBILITY COLUMN — ZERO READERS IN THIS SLICE
----------------------------------------------------
No endpoint, dashboard tile, or frontend reads ``visibility`` yet. This
is deliberate: a schema-first approach for a security-critical column.
Follow-up slices will query it for access-control filtering once a read
API exists.

ALEMBIC BRANCH NOTE
-----------------------
``dev-team/feat-143-obsidian-security-halted-wip`` (an unmerged branch)
carries migrations that also chain off ``l1i2j3k4a5b6``. This revision
ID was chosen to avoid an ID collision, but NOT a branch — when FEAT-143
resumes, re-point its first migration's ``down_revision`` to
``o1l2m3n4a5b6`` before merging, or Alembic will report multiple heads.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "o1l2m3n4a5b6"
down_revision: Union[str, None] = "l1i2j3k4a5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Load-bearing string — asserted verbatim by
# backend/tests/test_ontology_security.py::test_bare_update_rejects_visibility_promotion.
# This migration is immutable, so this substring must never be reworded.
_PROMOTION_ERROR = "promotion requires explicit path"


def upgrade() -> None:
    op.create_table(
        "ontology_entities",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("entity_type", sa.String(20), nullable=False),
        sa.Column("external_key", sa.String(255), nullable=False),
        sa.Column(
            "visibility", sa.String(10), nullable=False, server_default="private"
        ),
        sa.Column(
            "classification_checked_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_ontology_entities_user",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_ontology_entities"),
        sa.UniqueConstraint(
            "user_id",
            "entity_type",
            "external_key",
            name="uq_ontology_entities_user_type_key",
        ),
        sa.UniqueConstraint("id", "user_id", name="uq_ontology_entities_id_user"),
        sa.CheckConstraint(
            "entity_type IN ('person', 'project')",
            name="ck_ontology_entities_entity_type",
        ),
        sa.CheckConstraint(
            "visibility IN ('private', 'public')",
            name="ck_ontology_entities_visibility",
        ),
    )
    op.create_index("ix_ontology_entities_user_id", "ontology_entities", ["user_id"])
    op.create_index(
        "ix_ontology_entities_stale",
        "ontology_entities",
        ["user_id", "classification_checked_at"],
        postgresql_where=sa.text("visibility <> 'private'"),
    )

    op.create_table(
        "ontology_relationships",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source_entity_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("relationship_type", sa.String(30), nullable=False),
        sa.Column("target_entity_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "visibility", sa.String(10), nullable=False, server_default="private"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_ontology_relationships_user",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_entity_id", "user_id"],
            ["ontology_entities.id", "ontology_entities.user_id"],
            name="fk_ontology_relationships_source_entity",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_entity_id", "user_id"],
            ["ontology_entities.id", "ontology_entities.user_id"],
            name="fk_ontology_relationships_target_entity",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_ontology_relationships"),
        sa.UniqueConstraint(
            "user_id",
            "source_entity_id",
            "relationship_type",
            "target_entity_id",
            name="uq_ontology_relationships_edge",
        ),
        sa.CheckConstraint(
            "relationship_type IN ('contributed_to')",
            name="ck_ontology_relationships_relationship_type",
        ),
        sa.CheckConstraint(
            "visibility IN ('private', 'public')",
            name="ck_ontology_relationships_visibility",
        ),
    )
    op.create_index(
        "ix_ontology_relationships_user_id", "ontology_relationships", ["user_id"]
    )
    op.create_index(
        "ix_ontology_relationships_target_entity_id",
        "ontology_relationships",
        ["user_id", "target_entity_id"],
    )

    op.execute(
        """
        CREATE FUNCTION ontology_rank_visibility() RETURNS trigger AS $$
        DECLARE
            allow_promotion boolean;
        BEGIN
            allow_promotion := COALESCE(
                current_setting('app.allow_visibility_promotion', true),
                'false'
            ) = 'true';

            IF NEW.visibility IS NULL THEN
                RAISE EXCEPTION
                    'ontology visibility promotion requires explicit path: '
                    'visibility cannot be set to NULL';
            END IF;

            IF TG_OP = 'INSERT' THEN
                IF NEW.visibility IS DISTINCT FROM 'private'
                   AND NOT allow_promotion THEN
                    RAISE EXCEPTION
                        'ontology visibility promotion requires explicit path: '
                        'cannot insert row with visibility=% without '
                        'app.allow_visibility_promotion=true', NEW.visibility;
                END IF;
                RETURN NEW;
            END IF;

            -- UPDATE: demotion and no-op rewrites are always allowed.
            IF OLD.visibility = NEW.visibility THEN
                RETURN NEW;
            END IF;
            IF NEW.visibility = 'private' THEN
                RETURN NEW;
            END IF;
            IF NOT allow_promotion THEN
                RAISE EXCEPTION
                    'ontology visibility promotion requires explicit path: '
                    'cannot promote visibility from % to % without '
                    'app.allow_visibility_promotion=true', OLD.visibility, NEW.visibility;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql SET search_path = pg_catalog, public;
        """
    )
    op.execute(
        "CREATE TRIGGER ontology_entities_rank_visibility "
        "BEFORE INSERT OR UPDATE ON ontology_entities "
        "FOR EACH ROW EXECUTE FUNCTION ontology_rank_visibility()"
    )
    op.execute(
        "CREATE TRIGGER ontology_relationships_rank_visibility "
        "BEFORE INSERT OR UPDATE ON ontology_relationships "
        "FOR EACH ROW EXECUTE FUNCTION ontology_rank_visibility()"
    )


def downgrade() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS ontology_relationships_rank_visibility "
        "ON ontology_relationships"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS ontology_entities_rank_visibility ON ontology_entities"
    )
    op.execute("DROP FUNCTION IF EXISTS ontology_rank_visibility()")
    op.drop_table("ontology_relationships")
    op.drop_table("ontology_entities")
